container:
  image: goreleaser/goreleaser:latest

test:
  env:
    CIRRUS_WORKING_DIR: /go/src/github.com/$CIRRUS_REPO_FULL_NAME
  get_script: go get -t -v ./...
  test_script: go test -v ./...

release:
  depends_on:
    - test
  only_if: $BRANCH == "master"

  env:
    GITHUB_TOKEN: ENCRYPTED[7c2bf67b32d45b8dc19ad1369efd7a7816f7cfb1bf706e09feaa381f866ce9872c883fe8befaefa9f62c34632718b143]

  script:
    goreleaser release