before:
  hooks:
  # you may remove this if you don't use vgo
  #- go mod download
  # you may remove this if you don't need go generate
  #- go generate ./...
builds:
  - goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
